name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        runs-on: [macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - run: npm i
    - run: npm run publish
      env:
        GH_TOKEN: ${{ secrets.github_token }}